### ISSUE TITLE
Disabling News Feed Eradicator for a period of time does not work on Reddit

### ISSUE THREAD

**Issue by MTHSBGN** [jordwest/news-feed-eradicator#104]
When I turn off News Feed Eradicator for a period of time for Reddit, the feed remains hidden but the quotes disappear.

![Annotation 2020-11-09 122248](https://user-images.githubusercontent.com/17926472/98535382-4dbb1380-2286-11eb-95a8-065f9d2d1314.png)

**Comment by yujinyuz** [comment]
Can reproduce this issue

**Comment by pawlos** [comment]
it looks like it works ok from when running dev version from code. The released version has this flaw :/

**Comment by JesperDramsch** [comment]
The newest version seems to have fixed this. Works fine now.

**Comment by MTHSBGN** [comment]
Yes indeed, it works for me too. I'am closing the issue then.
