### ISSUE TITLE
Bug: posts in Facebook timeline still respond to mouse hover

### ISSUE THREAD

**Issue by ryanmonro** [jordwest/news-feed-eradicator#106]
Just noticed this today. Even with the timeline set to `display: none`, the timeline can still tell me about guitars I shouldn't be buying. Any thoughts of how to get around this?

<img width="911" alt="fb issue" src="https://user-images.githubusercontent.com/23104415/99733316-16195a80-2b15-11eb-94f3-29d5408b7677.png">

**Comment by jordwest** [comment]
Hi @ryanmonro, I wasn't able to reproduce this, are you still seeing this issue?

The feed isn't set to `display: none` as that was causing weirdness with the infinite scroll, but it does have `pointer-events: none`, so still shouldn't be happening 🤔

**Comment by ryanmonro** [comment]
Actually @jordwest I've tried a few times but can't get it to do it again, maybe it depends on which posts are in the feed? If it does still do it maybe it's unlikely. It's confusing that it happened at all though isn't it.

**Comment by jordwest** [comment]
There's a change in the latest version just published (2.2.0) that might possibly maybe perhaps fix it. The feed is now set to `position: absolute` with `width: 0` and `height: 0`, so fingers crossed that fixes it.

I'll close this for now, please reopen if you see it again. Thanks for the report!
