### ISSUE TITLE
Doesn't work anymore on facebook

### ISSUE THREAD

**Issue by Kiro24** [jordwest/news-feed-eradicator#110]
It has been working for a year now just fine. But recently, It stopped working on Facebook altogether (works on Twitter just fine). Though sometimes when I reload the news feed, it works only for this session and returns to not working again in a new session.

**Comment by jordwest** [comment]
Hey @Kiro24, I haven't been able to reproduce this. Can you send a screenshot and let me know your browser, version, and OS?

**Comment by jordwest** [comment]
Closing for now as I haven't heard any more reports, feel free to reopen with more details
