### ISSUE TITLE
I see LinkedIn and Youtube are added, but it doesn't get published to Chrome Appstore?

### ISSUE THREAD

**Issue by nvquanghuy** [jordwest/news-feed-eradicator#111]
It seems LinkedIn, Youtube are supported here: https://github.com/jordwest/news-feed-eradicator/tree/master/src/sites

But when I install the Chrome app it doesn't show anything? Do you guys need to publish the new version again to Chrome store?

**Comment by jordwest** [comment]
Ah yep, it's still sitting on master, and needs some bugs to be fixed before it goes out. The YouTube support currently breaks the comments section. I haven't been working on it for a while, but will get to it soon and they'll go out in the next release.

**Comment by aminoche** [comment]
Excited about this one!

**Comment by jordwest** [comment]
Currently pending review with Chrome web store, should be out in the next couple days!
