### ISSUE TITLE
Suggestion: YouTube feed

### ISSUE THREAD

**Issue by ginomeee** [jordwest/news-feed-eradicator#114]
Really appreciate the work that the devs have put on this and this plugin has helped me greatly in my everyday, however there's one thing that I'd like to suggest

Support for blocking the YouTube feed (homepage) would be great as it already blocks the vast majority of time wasting sites. Just a simple suggestion that I hope the devs and contributors would consider.

Thank you!

**Comment by jordwest** [comment]
Hi @ginomeee you’re in luck, I just published v2.2 with YouTube support yesterday :) 

It’s currently in review with the Chrome web store, so should be available in the next day or two.
