### ISSUE TITLE
Problem with Linkedin

### ISSUE THREAD

**Issue by flindner89** [jordwest/news-feed-eradicator#117]
The feed eradicator worked well for a few weeks. I use it on Youtube, Facebook, and Linkedin. 
Since I updated Google Chrome to Version 88.0.4324.150 (64-Bit) it doesn't work with Linkedin anymore. The Linkedin feed is displayed normally even though I activated the eradicator. 
OS: MS Windows 10 Home
Tried reboot the browser and system several times. The issue remains for 3-4 days now. 

Youtube and FB still work.

**Comment by jordwest** [comment]
Thanks for the report, confirmed on my end. Looking into it.

**Comment by kon3ktor** [comment]
Same here, but I'm using Firefox.
Thank you, Jordan

**Comment by msheng15** [comment]
Hi Jordan, I have the same problem as flindner89 and also use Chrome. The Newsfeed Eradicator for LinkedIn worked previously as well. Thank you!
