### ISSUE TITLE
Add Instagram!!!

### ISSUE THREAD

**Issue by gokul1078** [jordwest/news-feed-eradicator#118]
Thank you!!!

**Comment by rumeshmadhusanka** [comment]
Yes we need this feature too. 
There's an extension for Insta already. [https://github.com/rurush47/insta-feed-eradicator](url). But it would be nice to have everything in a single extension.

**Comment by jordwest** [comment]
Instagram support was added in 2.2.1 thanks to @ryanmonro, which should be out in the next day or two
