### ISSUE TITLE
LinkedIn eradicating doesn't work

### ISSUE THREAD

**Issue by kherzieandal** [jordwest/news-feed-eradicator#124]
I don't know if it's just me, it doesn't work on linkedin.

**Comment by romain-inxl** [comment]
Same here, that's not just you. Latest version of Chrome on Mac OS 10.15.7

**Comment by Romnoel** [comment]
Yeah, the LinkedIn feed shows for me too on Firefox on Windows. It's been like that for a while now I think

**Comment by jake-stika** [comment]
Same issue here on Firefox!

**Comment by KishenSharma6** [comment]
Also having the same issue with Chrome on MacOs 11.2.3

**Comment by dav-00** [comment]
Same issue on Chrome (89.0.4389.114) on Mac Mojave OS 10.14.6

**Comment by alelaraujo** [comment]
Some issue here, Chome (89.0.4389.114 (Official Build) (x86_64))on macOS 11.2.3 (Intel)

**Comment by edenvidal** [comment]
Same issue - Chrome Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by mikerayco** [comment]
Same here on my favorite browser, Firefox.

**Comment by jordwest** [comment]
Fixed in 2.2.1, should be out in the next day or two
