### ISSUE TITLE
dont work properly with new facebook version

### ISSUE THREAD

**Issue by arafat2201** [jordwest/news-feed-eradicator#125]
It works only in the newsfeed section. watch, marketplace, groups, and gaming sections also be eradicated.

**Comment by kubaczek2k** [comment]
Hi @arafat2201 
I think that is the main purpose to this add-on, to eradicate only news-feed on Facebook and sites like it.
From my experience I like to see what is going on with my groups on FB, that is why I am signed to them.
Watch and Gaming sections in my opinion are also good to consider of being able to block.
They are much more distracting than helping in find news by any means.
Cheers, Jakub

**Comment by jordwest** [comment]
Yes, for now we're only blocking the main feed to keep things simple, especially as support for more sites are added.

If you'd like to customise FB more, check out https://socialfixer.com/. It has much deeper customisation options.
