### ISSUE TITLE
LinkedIn support

### ISSUE THREAD

**Issue by d1mnewz** [jordwest/news-feed-eradicator#134]
eom

**Comment by d1mnewz** [comment]
Already partially done at https://github.com/jordwest/news-feed-eradicator/pull/89
Is there anyone who can review it? I can step in for resolving the comments

**Comment by mrtysn** [comment]
There's this other extension I use for [blocking LinkedIn](https://github.com/lucboruta/linkedin-feed-blocker), maybe they could be merged together

**Comment by JesperDramsch** [comment]
@jordwest any way the current commit state could be published as 2.2.1 to the Chrome store? Then Linkedin would work again as intended and it's been 3 months since the commit.

**Comment by jordwest** [comment]
2.2.1 is out for review by the stores now so should be fixed soon! Thanks all :+1:
