### ISSUE TITLE
[Suggestion] Add a button to uneradicated and eradicate back the page 

### ISSUE THREAD

**Issue by oussama-aouini** [jordwest/news-feed-eradicator#196]
I don't know if someone suggested this feature before or not, but I think it would be very useful, I have been using this extension for a couple of years to limit my social media usage nevertheless I usually take a quick look at the feeds and to turn off eradication I have to open the extension settings every time which I found repetitive and time consuming, it think it would be nice if there was a button in the eradicated page that you can click to uneradicate for predefined period of time

**Comment by wrabit** [comment]
if you're doing this enough to want a quicker way, it's kind of defeating the point.
