### ISSUE TITLE
loop in firefox

### ISSUE THREAD

**Issue by hungminhtran** [jordwest/news-feed-eradicator#20]
facebook loop when tried to reload script. 
[image](https://www.dropbox.com/s/611zsbfv3hgrde3/Screenshot%202016-05-08%2022.47.11.png?dl=0)

**Comment by jordwest** [comment]
Thanks for reporting. This seems to be happening to a few people in Chrome too, generally when the JS fails to load and replace the feed. Seems like Facebook thinks you're at the bottom of the news feed so it tries to load the next page.
