### ISSUE TITLE
Instagram News Feed no longer blocked

### ISSUE THREAD

**Issue by franznowak** [jordwest/news-feed-eradicator#203]
While news feed eradicator is working as expected, it seems to have stopped working for Instagram as of today (at least for me?)

**Comment by lucedes27** [comment]
Having the same issue.

**Comment by BellaBalou** [comment]
I am having this issue as well!

**Comment by schneiderkarel** [comment]
Same here :)

**Comment by yazan1107** [comment]
Having the same issue.

**Comment by mateuszkasprowicz** [comment]
Same here

**Comment by Laith-Alayassa** [comment]
Same issue here. I think that Instagram has changed the way it displays content because the extension's code has not been updated recently.

**Comment by 0xZF** [comment]
Same here

**Comment by aethos** [comment]
+1, same issue!

**Comment by aethos** [comment]
Added a PR here, should fix it. If anyone can help get the authors attention, we can merge it! https://github.com/jordwest/news-feed-eradicator/pull/205

**Comment by Italosayan** [comment]
same here

**Comment by jordwest** [comment]
As mentioned on #205, will hopefully get this fix out in the next couple days

**Comment by jordwest** [comment]
Fixed in v2.2.2, should be out in the next couple days after review

**Comment by schneiderkarel** [comment]
Thank you Jordan. :)

**Comment by franznowak** [comment]
Thank you!
