### ISSUE TITLE
Instagram feed not being blocked anymore.

### ISSUE THREAD

**Issue by kai-lovel** [jordwest/news-feed-eradicator#207]
With Instagram enabled in settings, it appears the IG feed is still appearing.

**Comment by jordwest** [comment]
Hi @kai-lovel, could you check which version you're running in your extension settings? This should be fixed in v2.2.2 but it only went out recently so your browser mightn't have updated yet

**Comment by jordwest** [comment]
Will close this as duplicate of #205 for now

**Comment by kai-lovel** [comment]
Thanks Jordan. Still on v2.2.1 but presume Chrome will push update shortly.

**Comment by kai-lovel** [comment]
Working ✅
