### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by fogich** [jordwest/news-feed-eradicator#21]
Any way to make it work for the android mobile version? Adding m.facebook.com, web.facebook.com, etc. as domains, I guess

EDIT: I see it's set to *.facebook.com, why is it not working on android then?

**Comment by jordwest** [comment]
NFE doesn't support mobile yet, or rather, mobile doesn't support NFE :)

Currently it seems like only Firefox for Android has support for browser plugins, but that might change soon.
