### ISSUE TITLE
Eradicator shows quote over unblocked twitter feed

### ISSUE THREAD

**Issue by mtamjidhossain** [jordwest/news-feed-eradicator#217]
Since the last one or two days, this is how it looks like on Twitter.

![image](https://user-images.githubusercontent.com/72858423/192094009-f28eb59a-b8aa-4c47-9712-f7a8585466d1.png)

**Comment by Szedresi** [comment]
Same here

**Comment by jucor** [comment]
Same here, very recent, wasn't the case a couple days ago.

**Comment by jakazzy** [comment]
Experiencing same here

**Comment by vinn2010** [comment]
Same

**Comment by jordwest** [comment]
Thanks for the report!

Should be fixed in 3853e66aa9adc16ca8887f605249a7b94eba9d23, will publish shortly.

**Comment by jucor** [comment]
Thanks a lot @jordwest for your work and reactivity!!
