### ISSUE TITLE
Not working on facebook

### ISSUE THREAD

**Issue by MohamedAliRashad** [jordwest/news-feed-eradicator#218]
The extension stopped working on facebook for some reason

**Comment by laleaton** [comment]
same for me

**Comment by walpolsh** [comment]
yup!

**Comment by jordwest** [comment]
Hmm, it's still working for me, so it's possible FB is rolling out a change to different cohorts.

Can someone who's having this problem please run this in the browser console from the Facebook homepage:

```
document.querySelector("div[role='feed']") == null 
```

And let me know what it returns

**Comment by pgduval** [comment]
i'm having the issue. the command returns "true"

**Comment by lukechadwick** [comment]
> Hmm, it's still working for me, so it's possible FB is rolling out a change to different cohorts.
> 
> Can someone who's having this problem please run this in the browser console from the Facebook homepage:
> 
> ```
> document.querySelector("div[role='feed']") == null 
> ```
> 
> And let me know what it returns

Returns true for me. Probably the class/attributes changed.  `[role="main"]` should work as a selector instead.

![image](https://user-images.githubusercontent.com/6725655/192413235-9d8b2595-431b-4825-b530-1886c28d4f02.png)

**Comment by Niirdla** [comment]
> The extension stopped working on facebook for some reason

same for me

**Comment by jordwest** [comment]
Ahh yep sounds like they've made some changes that haven't been pushed out to everyone yet.

`[role="main"]` would likely remove too many UI elements, here's where `role="feed"` appears on my FB relative to `role="main"`, can you see any equivalent attribute we could use as a selector for that element?

![Screen Shot 2022-09-27 at 12 11 13 pm](https://user-images.githubusercontent.com/416133/192415630-bc855222-8dd6-470f-9ad3-8f5d3b361472.png)

**Comment by lukechadwick** [comment]
Perhaps this
![image](https://user-images.githubusercontent.com/6725655/192417327-3d6cbb07-e7f0-4048-89e4-29eb9e88708c.png)

This element contains all the news feed items so `#ssrb_feed_start + div` works

**Comment by jordwest** [comment]
Ah awesome find, yep that should do it. I've pushed the change to master, could you try this build and see if it fixes it on yours?

[NewsFeedEradicator_v2.2.2-3-gcd47dcd.zip](https://github.com/jordwest/news-feed-eradicator/files/9651030/NewsFeedEradicator_v2.2.2-3-gcd47dcd.zip)

Chrome: [Install extension from file](https://ui.vision/howto/install-chrome-extension-from-file) 

Firefox:
![Screen Shot 2022-09-27 at 12 46 25 pm](https://user-images.githubusercontent.com/416133/192419952-c914bb48-d7a8-430d-b6ca-ca730f4ca933.png)
![Screen Shot 2022-09-27 at 12 47 55 pm](https://user-images.githubusercontent.com/416133/192420264-92dd62b8-6a89-47d3-82b7-a8a49c26cd2d.png)
![Screen Shot 2022-09-27 at 12 48 02 pm](https://user-images.githubusercontent.com/416133/192420309-f820f0b3-df98-4e4e-8dd1-eae4d9dc8dcd.png)

**Comment by lukechadwick** [comment]
@jordwest yep that works fine. Thank you!

![image](https://user-images.githubusercontent.com/6725655/192420759-c1ea05a3-292d-4f01-a1e9-bbc70e2f2cde.png)

**Comment by jordwest** [comment]
Excellent, thanks for debugging this one with me! Will publish it to the addon stores shortly.
