### ISSUE TITLE
As of 26.09.2022, Facebook feed is not being hidden anymore

### ISSUE THREAD

**Issue by ishimarumakoto** [jordwest/news-feed-eradicator#220]
Facebook probably updated the div's / ids and now the news feed eradicator does not work with it anymore.

Thanks for the great work.

**Comment by jordwest** [comment]
Hi, could you try the build here:
https://github.com/jordwest/news-feed-eradicator/issues/218#issuecomment-1258895143

Or just wait a day or two for your extension to update to v2.2.3
