### ISSUE TITLE
Extension breaks sometimes on twitter

### ISSUE THREAD

**Issue by Ochuwa-sophie** [jordwest/news-feed-eradicator#221]
Great job with this. 
Today, I opened Twitter about 3 times and was able to read new tweets. The quote was displayed on top of the topmost tweet and I was also able to click on the tweet on which the quote was positioned. I don't have screenshots because it has fixed itself but I assume this is something y'all can investigate.

Great job again on this amazing tool.

**Comment by jordwest** [comment]
Please check that you're on v2.2.3, which was published earlier today.

Closing as duplicate of #218 for now.
