### ISSUE TITLE
Twitter feed not blocked anymore

### ISSUE THREAD

**Issue by paulstrobel** [jordwest/news-feed-eradicator#223]
In my case the News Feed Eradicator is not blocking the twitter feed anymore (see screenshot below).

Setup:
Brave: 1.43.93
Chromium: 105.0.5195.127
macOS: 12.6

![Screenshot 2022-09-27 at 16 07 05](https://user-images.githubusercontent.com/15238058/192549144-4ffe9126-c7f2-4a6c-95f1-a91eb9a53f78.jpg)

**Comment by lukaszdab** [comment]
I confirm, the issue is still present. My NFE version is 2.2.3 (as downloaded from the Chrome Store)

**Comment by StaniKub** [comment]
I also confirm this issue. Version 2.2.3

**Comment by SylvainSalgatHEIG** [comment]
Same issue in 2.2.4 with Firefox...

**Comment by tobiascornille** [comment]
For me, it works again when I change the language to English.

**Comment by antoine-sch** [comment]
Ahh thanks @tobiascornille! That was the issue! I was running in French. Thank you very much.
