### ISSUE TITLE
Facebook News Eradicator Not Working on Chrome

### ISSUE THREAD

**Issue by MyAhzzieBaby** [jordwest/news-feed-eradicator#234]
Started yesterday evening, and still not being eradicated today. Not sure what to do (I'm not techy). I tried turning the eradicator off and back on. Still not working. :(

**Comment by Pgee991** [comment]
Same! :/ Can someone fix this for us non-techy guys? 🙏

**Comment by lukechadwick** [comment]
New selector that works well enough for the main feed at least:

`[role="navigation"] + [dir="auto"] + div`

```
[role="navigation"] + [dir="auto"] + div {
    display: none !important;
}
```

**Comment by jordwest** [comment]
Thanks for reporting, please follow #232 for updates. Closing this as duplicate for now.
