### ISSUE TITLE
Stopped working on facebook

### ISSUE THREAD

**Issue by cschoreisz-pillar** [jordwest/news-feed-eradicator#240]
Hello !

This extension stopped working on facebook, and I've started scrolling again 😱 I've tried uninstalling and reinstalling the extension. If it helps, I'm on a Macbook pro Intel 2019, my Chrome version is Version 107.0.5304.87 (Official Build) (x86_64), and I'm working with my work Google account. Maybe the latter has established restrictions to third party extensions ? I wonder if it's happening to other people.

Hoping someone can help!

**Comment by boutterudy** [comment]
I experience the same issue, I'm on a XPS 13 9380, Windows 10 Family (21H2) and I'm using Chrome version 107.0.5304.88 (Official Build) (64 bits).

**Comment by yothrowawaytoday** [comment]
Also happening to me. Was working this morning

Windows 10 21H2 
Chrome Version 107.0.5304.89 (Official Build) (64-bit)

**Comment by slothendk** [comment]
Same for me. Mac Pro Intel mid 2014. Chrome version is 107.0.5304.110 (Officiel version) (x86_64).

**Comment by ethrane** [comment]
MacBook Air (M1, 2020), Chrome Version 107.0.5304.87

**Comment by tangmus1** [comment]
Same issue. Macbook Pro Early 2015 Intel, Chrome 107.0.5304.110

**Comment by lilboomer2606** [comment]
Same. Lenovo Legion 5, AMD Razen 7, Window 11 21H2, Firefox 106.0.5

**Comment by ethrane** [comment]
Randomly working again.

**Comment by cschoreisz-pillar** [comment]
Same here ! I'll close that thread !

**Comment by yothrowawaytoday** [comment]
Looks like the issue is back. Not eradicating for me again

**Comment by ethrane** [comment]
Same.

**Comment by cschoreisz-pillar** [comment]
Argh dang it ! Reopening

**Comment by AprilMason0101** [comment]
Still not working. :( I loved this extension.
