### ISSUE TITLE
Not working on Facebook! Plz fix it!

### ISSUE THREAD

**Issue by congthangnguyenvn** [jordwest/news-feed-eradicator#242]
Not working on Facebook! Plz fix it!
![2022-11-10_125107](https://user-images.githubusercontent.com/45443614/201011317-932a068b-1361-4de0-be86-c2936734cc9d.png)
![2022-11-10_125120](https://user-images.githubusercontent.com/45443614/201011323-1644d07f-1e3a-4b57-a4cd-45352e836ffa.png)

**Comment by Klesx** [comment]
Fixed, you can close this issue
