### ISSUE TITLE
This plugin and infinite scroll don't play super well together

### ISSUE THREAD

**Issue by bichiliad** [jordwest/news-feed-eradicator#25]
If you trigger infinite scroll (i.e. by scrolling to the bottom of the page), it tries to load new content until the bottom of the page is pushed out of the viewframe. When this plugin is enabled, that never happens and it loads forever (hooray). 

Steps to reproduce:
1. Enable the plugin / go to facebook.com
2. Scroll to the bottom of the page. 
3. Check out all those network requests

**Comment by NeeksGit** [comment]
+1 for this issue.

**Comment by heldersantosmoreira** [comment]
+1 for this

**Comment by jordwest** [comment]
This is now fixed in v1.0.2
