### ISSUE TITLE
Facebook infinity loading

### ISSUE THREAD

**Issue by Holicz** [jordwest/news-feed-eradicator#26]
While this extension is activated Facebook is loading infinitely. It finish loading and immediately start new one. So it make about 2 loading per seconds. It is also causing lags while writing in chat.

**Comment by willycamargo** [comment]
This bug bothers me :/

I'm using [Kill news feed](https://chrome.google.com/webstore/detail/kill-news-feed/hjobfcedfgohjkaieocljfcppjbkglfd) for a while

**Comment by jordwest** [comment]
@Holicz @willycamargo Infinite scrolling is now disabled in v1.0.2 and things are much snappier. Was a sneaky one to fix!
