### ISSUE TITLE
[Feature] Time > Money? User respects time: Deduct Money for extra time taken

### ISSUE THREAD

**Issue by anurag01a** [jordwest/news-feed-eradicator#267]
Whenever the user prompts again to get more hours for any social media, money should be deducted from user's account. This way the creators of NewsFeedErad can also earn amounts based on the user's distraction eventually decreasing it for user's good.

**Comment by jordwest** [comment]
Haha, I love the idea but I don't have any plans to make money from this extension. I feel that any monetary incentive would go against the point of it.

Appreciate the thought though :)
