### ISSUE TITLE
Twitter Issue

### ISSUE THREAD

**Issue by Hiltor** [jordwest/news-feed-eradicator#269]
Hi, I wanna start with a big "thank you" for this useful tool you gave us for free. 

I have an issue concerning Twitter, beside the addictive thing : News Feed Eradicator seems to fail eradicating the feed... Any help to fix this is welcome or any bug fixes ? 
(this bug is here for months now, and i didn't see any post about it here...) 
(I'm on Firefox, MacOS) 

Again, thank you for the good work :) 

<img width="1440" alt="Capture d’écran 2023-07-27 à 09 06 30" src="https://github.com/jordwest/news-feed-eradicator/assets/140692697/f8e6cd1c-9bec-4db5-8c4c-2d80879463f7">
<img width="614" alt="Capture d’écran 2023-07-27 à 09 06 20" src="https://github.com/jordwest/news-feed-eradicator/assets/140692697/578ae896-a2e8-414c-bbc7-d6de2b884a09">

**Comment by mdleung** [comment]
Have you tried isolating all the extensions you have?

**Comment by redsigma** [comment]
Doesnt work on firefox.

**Comment by jordwest** [comment]
Hi, this is a known issue when using Twitter in languages other than English, I'll look into a fix in the next release

**Comment by Hiltor** [comment]
It's fixed ! Thanks a lot ! :D 👍
