### ISSUE TITLE
Port to Web Extension

### ISSUE THREAD

**Issue by bogas04** [jordwest/news-feed-eradicator#28]
Since Firefox 48, WebExtensions are supported and you can simply use your chrome extension for Firefox from the looks of it.

**Comment by jordwest** [comment]
Ooh, this is nice, thanks for the tip! The issue last time was passing Firefox's strict for review to get published in addons.mozilla.org, I wonder if the requirements have been relaxed for WebExtensions.

The reason it was rejected was for minification and bundling of vendor code (React JS) using webpack, and I didn't have the time to look into altering that. This might be a good chance to revisit.

**Comment by jordwest** [comment]
Looks like there shouldn't need to be any major changes to support WebExtensions, awesome!

Since the remaining hurdle is getting it accepted in the Firefox add-on store (tracked in #12) closing this for now.

**Comment by bogas04** [comment]
Amazing ! Thanks for looking into it! I was using [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) thus far to use your extension, and it just worked!

**Comment by jordwest** [comment]
Nice! I'd never heard of that extension. I'll leave a note in #12 for others who might be following.

**Comment by jordwest** [comment]
Just tested the Chrome build in Firefox Developer Edition, worked right out of the box! 🎉 

![screen shot 2016-12-10 at 7 57 51 pm](https://cloud.githubusercontent.com/assets/416133/21072574/20a4ee78-bf13-11e6-83c8-999391f2e408.png)
