### ISSUE TITLE
Avoid reloading the page several times

### ISSUE THREAD

**Issue by RobinVogel** [jordwest/news-feed-eradicator#29]
When I start facebook, the page reloads (F5) automatically a certain number of times before it stops.
It lasts like 20 seconds and the blinking icon (from facebook to loading) on the tab is distracting.
I'm on chromium.
Can it be fixed ?
Thank you,

Robin

**Comment by jordwest** [comment]
Should be fixed by 457e3f12e683dc3ebf9db540eafb2846aaceb923. Closing for now, please reopen if you still see issues.
