### ISSUE TITLE
NFE settings page keeps popping up when opening Social Media sites it blocks

### ISSUE THREAD

**Issue by DJCanuto** [jordwest/news-feed-eradicator#302]
This just started like last week or so, everytime I open Facebook or Reddit or some other sites NFE is currently blocking, the NFE page keeps creating new tabs. Like when I right click a Facebook link to open a new tab, another NFE page tab will open with it.

**Comment by LPTK** [comment]
I have the same problem! I wonder if it's a bug or a (very annoying) new "feature".

**Comment by jordwest** [comment]
Yeah this should definitely not be happening. It's likely related to the recent upgrade but I haven't been able to reproduce it on my end to be able to track it down.

Does it happen with every link, as soon as the page is loaded, or does it only happen sometimes? What OS are you using? Any tips to reproduce?

**Comment by LPTK** [comment]
MacOS and the Edge browser.

> Also do you have any sites showing "Needs permissions" on the settings page?

Great question! I did have one needed permission. As soon as I granted it by clicking on the button, this popup bug stopped happening :^)
