### ISSUE TITLE
Automatically opens config when writing url or after opening site (since 2.3.0?)

### ISSUE THREAD

**Issue by plagasul** [jordwest/news-feed-eradicator#311]
I believe that since 2.3.0 (unsure) or just recently, on chrome v 127.0.6533.72 (Build oficial) (64 bits)
 linux, the config page that allows me to select viewing time for the websites, pops while writing the url of one of the sites, or when opening the site.

Before I recall, the config page only opened when manually clicking on the link at IG or FB.

Is this by design or something about my installation that changed?

It is very annoying, not always I want to access that page, it fires out on itself.

thank you

**Comment by jordwest** [comment]
Do any of the sites show "needs more permissions"? If so, try clicking on that site and enable the extra permissions

**Comment by plagasul** [comment]
Yes, that is correct, one site was demanding "needs more premissions", after answering that it does not seem that the extension is opening when typing urls or visiting sites. Perhaps it'd make sense if that happened only for sites whose permissions are needed.

Thank you
