### ISSUE TITLE
Linkedin - Other sections other than newsfeed also 'eradicated' (Firefox)

### ISSUE THREAD

**Issue by silvaDominic** [jordwest/news-feed-eradicator#315]
## Steps to reproduce
1. Install Firefox
2. Install plugin
3. Sign into LinkedIn
4. Observe news feed is 'eradicated'
5. Go to any of the following other sections: notifications, jobs, messages
6. Observe these sections are also 'eradicated'

## Expected Result
Only news feed should disappear.

## Actual Result
Other sections disappear.

### News Feed (Works as expected)

![Screenshot 2024-10-11 at 18-50-54 Feed LinkedIn](https://github.com/user-attachments/assets/7e9d5f45-a7ee-4549-b0f9-88f47310778e)

### Jobs

![Screenshot 2024-10-13 at 17-51-58 Jobs LinkedIn](https://github.com/user-attachments/assets/ed4a237e-54d4-429e-a64a-6923662dc161)

### Notifications

![Screenshot 2024-10-11 at 18-51-59 Notifications LinkedIn](https://github.com/user-attachments/assets/4ff37a9a-daa8-40ba-b803-7fc729a7048f)

### Messages

![Screenshot 2024-10-11 at 18-51-42 Messaging LinkedIn](https://github.com/user-attachments/assets/7ec997a7-6e1e-4f24-8508-1f2273ec2b6b)

## Additional Context
- "My Network" section appears to be unaffected.
- I noticed that refreshing the page will fix the issue, but it will still occur on initial load of the page if in a new browser window or tab.

## Operating System
Windows 10

## Browser
Firefox 131.0.2

## Plugin Version
2.2.7

**Comment by jordwest** [comment]
This should hopefully be fixed in build v2.3.1 pending review on Chrome web store now, reopen if not
