### ISSUE TITLE
Match Facebook subdomains in the Chrome version

### ISSUE THREAD

**Issue by sdsingh** [jordwest/news-feed-eradicator#33]
In the Firefox add-on, News Feed is disabled for all subdomains of Facebook (i.e. *.facebook.com).

This is unfortunately not true in Chrome, where only www.facebook is matched. I can submit a pull request for this feature if that's easiest for you?

**Comment by jordwest** [comment]
Hey @sdsingh, are you still interested in submitting a PR for this?

**Comment by sdsingh** [comment]
Sorry, completely missed this. Thanks for making the change @rickychilcott!
