### ISSUE TITLE
Bug: Keeps reloading forever

### ISSUE THREAD

**Issue by arieljannai** [jordwest/news-feed-eradicator#38]
Facebook keeps reloading over and over when the extension is enabled.
I've check a bit, and it seems it can't access `error.facebook.com` (probably ublock is denying it).

Any idea how can I get it to work properly while still using ublock?

Thanks!

**Comment by jordwest** [comment]
@arieljannai are you still seeing this issue? I'm not able to reproduce it.

If anybody continues to see this please reopen.
