### ISSUE TITLE
Feature Request--Top 5 stories

### ISSUE THREAD

**Issue by jntrcs** [jordwest/news-feed-eradicator#39]
Sorry this probably isn't the right place to post this, but I'm really interested if any developers who have forked this repository have attempted to make the eradicator limit the number of stories shown instead of eradicate them all. A killer feature for me would be to view the top 5 stories, but not allow scrolling. Facebook's algorithms do a fantastic job (for me) of putting what I'm actually interested in at the top of my feed, and I would love to see people's important announcements without getting distracted by eight miles of memes. If anyone has already worked on this I'd love to see it!

As a side note, Facebook posts get marked as "have seen" when scrolled past (which is why you don't see the same announcement at the top of your feed every time you log in). Does anyone know if the eradicator prevents this switch from getting flipped, or does it mark what would have been seen as seen?

**Comment by jordwest** [comment]
Hey there, this is a cool idea, but selectively showing stories is fairly involved and not something I currently have time to implement.
