### ISSUE TITLE
Feature request -- block stories

### ISSUE THREAD

**Issue by therobinkim** [jordwest/news-feed-eradicator#40]
Facebook has released a new feature that resembles Snapchat and Instagram Stories, where Facebook users can post pictures/videos that are shared with their friends for only a day.

These stories are now appearing on the top-right corner of my Facebook newsfeed.

Feature request: let's get the Chrome Extension set up so we can get rid of this! 😄

**Comment by daivinhtran** [comment]
Is the project still being supported?

**Comment by 8BitRain** [comment]
I would assume this project is being supported. If the author doesn't reply
back lets brainstorm on some ways to include this feature?

**Comment by daivinhtran** [comment]
@8BitRain how would we deploy the change if we don't own the project?

**Comment by therobinkim** [comment]
We would have to deploy a separate extension.

**Comment by 8BitRain** [comment]
@therobinkim Can we that if we fork the branch and then build our changes?

# Build output:
build                           # The raw extension contents for each browser
dist                            # Distributable extension package for browsers

**Comment by therobinkim** [comment]
I imagine we would be able to, but I think it'd be great if we could try to reach @jordwest via email first! In the meantime, we could work on a PR to halp address this issue. I can't work on this until the weekend at the earliest   Anybody want to call dibs? Otherwise, I'd be happy to get to it when I can.

**Comment by stephenpcook** [comment]
I would suggest giving the owner a little more time before considering e-mailing him; it is, after all, a feature request posted less than a week ago.
Incidentally I can't see said stories. I did manage to remove the (empty) ticker box with a user script, so that approach might tide you over if these are distracting.

@8BitRain Might it be added in [src/lib/remove-news-feed.ts](https://github.com/jordwest/news-feed-eradicator/blob/4ade9c4d7d0d9bd7119b9a4cf92c22d57e7d0956/src/lib/remove-news-feed.ts)?

**Comment by jordwest** [comment]
Hey there, I'm happy to merge in and deploy a PR to remove the stories - if anybody is keen to implement it that would be 👌

> Might it be added in src/lib/remove-news-feed.ts?

Yep, assuming the class/id of the element is somewhat predictable, it could be added to `elementsToRemove` at the top of that file.

**Comment by daivinhtran** [comment]
Thanks, @jordwest ! I'll give it a shot

**Comment by stephenpcook** [comment]
As mentioned [above](https://github.com/jordwest/news-feed-eradicator/issues/40#issuecomment-329427696), I can't actually see these stories. Can someone verify this address the issue before I create a pull request, @therobinkim ?

**Comment by 8BitRain** [comment]
<img width="1052" alt="screen shot 2017-09-16 at 9 03 38 am" src="https://user-images.githubusercontent.com/1919967/30513818-8973aeee-9abe-11e7-8bc1-826ca6f34ddb.png">

@stephenpcook I would also like to give this PR request a go.

**Comment by stephenpcook** [comment]
@8BitRain Well I think it's removed by stephenpcook@62c67c93259c64399d2b5cb37697699204e408f3 (going by [your post](https://github.com/jordwest/news-feed-eradicator/issues/40#issuecomment-329237000)), but I do not have the stories feature, hence I cannot test it.

**Comment by stephenpcook** [comment]
A "stories" bar finally showed up, and the commit successfully removed it, so I created a PR. I guess the Story has now expired, because the bar is no longer there, with of without news feed eradicator.

**Comment by andrewschreiber** [comment]
Wanted to note that you can use adblock to block the stories as well.

Go to
![image](https://user-images.githubusercontent.com/1892071/32138248-3e6de134-bbe4-11e7-8e41-899e2718c8c9.png)
and add
**www.facebook.com##[id="fb_stories_card_root"]**
to the list at the bottom

**Comment by stephenpcook** [comment]
I've removed them with a short userscript and TamperMonkey; the PR is good to go.

**Comment by jordwest** [comment]
@stephenpcook's [PR fixed this](https://github.com/jordwest/news-feed-eradicator/pull/43), closing
