### ISSUE TITLE
Add instagram support

### ISSUE THREAD

**Issue by PatMyron** [jordwest/news-feed-eradicator#47]
With jQuery enabled,

`$('._owark').remove();`

currently gets rid of the Instagram feed for me. However, I'm not sure if this classname changes over time.

**Comment by jordwest** [comment]
This should be possible in future once we've sorted out the permissions issue (#50)

**Comment by PatMyron** [comment]
Didn't realize Chrome extensions had programmatic permission requests in addition to manifest defined permissions. Google moved Android towards that model as well a bit ago. Let me know if you want any help with the code. This could be useful for even more sites like Twitter, LinkedIn, etc as well.

**Comment by PatMyron** [comment]
`$('.stream').remove();` works for twitter

`$('.core-rail').remove();` works for linkedin 
`$('.relative').remove();` looks better for linkedin, but items come back if you scroll after

**Comment by jordwest** [comment]
Merging this into #63
