### ISSUE TITLE
Use opt-in host permissions model

### ISSUE THREAD

**Issue by jordwest** [jordwest/news-feed-eradicator#50]
Instead of declaring all host permissions in the manifest, host permissions should be requested programmatically when they're needed.

This avoids the situation where adding a new host (eg, m.facebook.com) to the manifest automatically disables the entire plugin for existing users until they allow the new permissions. Instead, we can ask only for the new permission when it's required, or after the upgrade.

**Comment by valioDOTch** [comment]
Are you working on this?
Else I consider doing this.

**Comment by jordwest** [comment]
@valioDOTch that would be great!
