### ISSUE TITLE
Count the amount of posts that were successfully eradicated from your feed

### ISSUE THREAD

**Issue by mothnode** [jordwest/news-feed-eradicator#52]
Not sure how to go about it - but it would be a nice feature. Sorry if I'm posting it in a wrong place!

**Comment by pburtchaell** [comment]
This could be tricky because I'm sure the FB news feed loads posts asynchronously... but perhaps there's a way.

**Comment by jordwest** [comment]
Cool idea! Right now it's pretty dumb (simple) and just deletes the entire feed element, adding this feature would require adding quite a bit of complexity and understanding of posts, it's not something I'm willing to compromise code simplicity for at the moment.
