### ISSUE TITLE
Can we make eradication publisher specific??

### ISSUE THREAD

**Issue by gauravgrover95** [jordwest/news-feed-eradicator#58]
I want to see posts just from some specific loved ones. But not all the other disturbing/distracting things that Facebook decides to put up on my face to determine what I like or dislike. 

Do you think we can do it? 

P.S. I wish to be a contributor.

**Comment by jordwest** [comment]
Sorry, that's not really the goal of this project. You can still visit individual people's pages if you want to. You might like to try something like [Social Fixer](https://chrome.google.com/webstore/detail/social-fixer-for-facebook/ifmhoabcaeehkljcfclfiieohkohdgbb?hl=en) which has a lot of configuration/customisation.
