### ISSUE TITLE
More quotes!

### ISSUE THREAD

**Issue by lusa** [jordwest/news-feed-eradicator#6]
Hello. Can there be more quotes? I haven't looked into where you guys add quotes, but I've been using this for a long enough period to know that there are only about 10-15 of them and I know all of them by heart at this point so I think there could easily be support for a new one every day. I could make this enhancement if someone could direct me to where. Thanks!

**Comment by jordwest** [comment]
The quotes list has now been extracted out to `/src/quotes.js` which should make editing the quotes easier. There will be more quotes added in the next release.

**Comment by adamthomson** [comment]
Coooool. :+1:

**Comment by adamthomson** [comment]
Coooool :+1:

**Comment by mikespax** [comment]
Idk if more quotes have already been added, but I still want more please. :) I like sitting there and refreshing the page until I get motivated to close the tab and get back to work. :)

**Comment by michalzubkowicz** [comment]
Looking forward for it!

**Comment by troggy** [comment]
Inspirational quotes API: http://forismatic.com/en/

**Comment by jordwest** [comment]
Closing this now that it's possible to add your own quotes :)
