### ISSUE TITLE
Eradicate feeds on other sites

### ISSUE THREAD

**Issue by jordwest** [jordwest/news-feed-eradicator#63]
One common request is for this to work on sites other than Facebook. I think this is achievable once #50 is complete. Please use this issue for requests for other sites.

- [x] Instagram
- [x] LinkedIn - #89, #101 (coming in v2.2.0)
- [x] Youtube - ba78134227c0ccfa09648ac4b76ff8c1c7326ca5 (coming in v2.2.0)
- [x] Twitter - #92 (landed in v2.0.0)
- [x] Reddit - #98 (v2.1.0)
- [x] HN - #97 (v2.1.0)

**Comment by jordwest** [comment]
Twitter support has landed in v2.0.0 which is live on Firefox, with Chrome to follow shortly

**Comment by gabrielpaipa** [comment]
This is an amazing feature. I think this is exactly what I'd like to see in another platform, Reddit. I _do_ want to access specific subreddits, and News Feed Erradicator would be the perfect tool to be able to access those communities and yet not get stuck in the Main Page rabbit hole.

**Comment by ryanmonro** [comment]
I've added pull request #105 for Instagram support. Thanks for refactoring to make it so easy to add more sites, this is great!

**Comment by ckrf** [comment]
The LinkedIn blocker has stopped working for me recently

**Comment by shbach** [comment]
LinkedIn newsfeed also isn't being hidden for me.

**Comment by martonmedveczky** [comment]
Same here: LI doesn't work :(

**Comment by jordwest** [comment]
All sites in the original issue are now implemented, so I'm closing this for now. LinkedIn support was also fixed in 2.2.1, which should roll out over the next day or two.
