### ISSUE TITLE
Allow user to click to see his feed

### ISSUE THREAD

**Issue by ripper234** [jordwest/news-feed-eradicator#66]
I'd like to use News Feed Eradicator to eliminate the feed by default, but still allow me to click somewhere to see the feed now, if I choose. You can even display a prompt asking "Are you sure you want to spend your attention browsing facebook now?" to make sure people opt-in consciously.

A page refresh would return the feed to its default state - hidden.

**Comment by 1vasari** [comment]
You can pretty easily disable the extension in `chrome://extensions` to do this.

**Comment by obsd** [comment]
I thought about click to see the next item in the feed this will cause the user to take action for each post he wants to see and we can limit this to 10.
If you interested in such feature, I probably can create a pull request with it

**Comment by jordwest** [comment]
There's now a temporary disable function, you can access it by clicking the "News Feed Eradicator" footer or the icon in the browser toolbar
