### ISSUE TITLE
Feature: Simple Extension Toggle

### ISSUE THREAD

**Issue by maxsu** [jordwest/news-feed-eradicator#74]
Procedure to temporarily disable the extension is somewhat laborious & distracting, and tempts the user with the option to uninstall the extension:

1. Navigate to about:addons (distracting / may take multiple clicks)
2. Disable the app (user loss point)

#### A more subtle approach...
... is less distracting, but does not tempt the user to disable the addon (ie, it's somewhat hidden). In general, the disable eradicator button could live in the eradicator settings menu, above the "removal instructions" button. In firefox, a subtle disable/enable workflow could depend on the firefox overflow menu:

1. Add a "disable newsfeed eradicator" button in the user's overflow menu
2. The same button enables newsfeed eradicator again

To help the user re-enable, here are two possibilities:

1. Add an "enable newsfeed eradicator" button on top of the newsfeed when disabled
2. Add a timer for temporary disable
    - Timer may be standardized (fixed at, say 10 minutes), or configurable in settings

#### There are some risks:

1.  General disable button: The ease of disabling the addon may lead to a weaker facebook reduction effect
    - This may balance out with better user retention - a study would be ideal
    - Could have bugs, leading to unexpected behaviors and poor user outcomes
2. Overflow menu: Users may now know about the overflow menu / may dislike using it
   - Only provides solution for firefox users
3. Timer:  Could stress users
   -  stress enables compulsive FB use / can trigger user loss
   - It's not clear how to automatically enable eradicator without potentially disrupting important content (reading an important post, writing a comment, etc)

#### Conclusion

A subtle addon disable button could lead to higher user retention and satisfaction, at the cost of weakening the addon's facebook reduction effect. I suspect it's best to err on the side of improved user experience and trust the user to be responsible - to a degree - but timers and a blatant "enable eradicator" button can help users return to a newsfeed free experience. There are some risks inherent here, mainly implementation bugs and unexpected user loss; testing can help determine  the advantages/disadvantages of this feature cluster.

**Comment by jordwest** [comment]
Hey @maxsu, thanks for the detailed suggestion! This is one of the most long requested features, and I've finally got around to implementing something like the timer option you've suggested.

As it's currently implemented, it immediately hides the feed when the timer expires, which could be a little annoying. I like the idea of showing an "enable" button again while the feed is visible, and I'm thinking it might also be good to show a countdown near the feed so it's not quite as much of a shock when the feed disappears. Will see how it goes as is, and maybe these are improvements that can be made in future.
