### ISSUE TITLE
Idea: Be able to like and comment on the Quotes!! :-p

### ISSUE THREAD

**Issue by chongkan** [jordwest/news-feed-eradicator#78]
The quotes are so good they really get me thinking, wanting to discuss them and wanting to like them and share, and tag people on them!

**Comment by stephenpcook** [comment]
Reading comments on quotes sounds like the sort of distraction I'm trying to eradicate 😆

**Comment by gabrielpaipa** [comment]
I agree with stephenpcook. The quotes should not mirror the platform we are trying to avoid. Chongkan, you could share the quotes with your friends via Facebook.

**Comment by jordwest** [comment]
Yep sorry @chongkan, this isn't going to happen. Maybe share them with people in real life? :)
