### ISSUE TITLE
Request for help: Updating to work with Facebook Beta

### ISSUE THREAD

**Issue by jordwest** [jordwest/news-feed-eradicator#82]
Recently Facebook has been experimenting with a new UI and it breaks News Feed Eradicator.

Unfortunately Facebook hasn't (yet?) given me access to this new UI, so it's hard for me to work out exactly which DOM elements need to be removed and how to remove them, but more importantly its difficult to test the changes.

So, this is a call to arms! If you're a dev and have access to the new Facebook UI, I need your help! I realise this project has been a little neglected lately, but I'll be sure to make time to be here to help and expedite any PRs that fix this as it's affecting a lot of people right now. Thousands of people will be grateful for this work, especially at this time when many of us are stuck at home.

If you're interested, read on.

## Tech details

There are a few basic parts to news feed eradicator:
1. Hiding the feed with CSS immediately, before the JS loads
2. Removing the actual feed elements
3. Injecting the news feed eradicator element that displays the quote and other UI

I've had a brief go at getting these to work after looking at a friend's account (who has access to the beta) and using the inspector.

It seems the new UI has been rewritten in React, which is likely to make things a little more difficult. The classnames are all hashed - we can't use that to determine which element contains the feed as they might change whenever the css rules change.

Fortunately, they have added ARIA roles, including [`role="feed"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Feed_Role) which is likely what we want.

What I've done is move the logic that removes the "old" feed into `src/sites/fb-classic.ts`, and copied that into `src/sites/fb-2020.ts` for the new beta. The logic that decides which fb is currently in use isn't working currently, but it just falls back to the 2020 version anyway. We can fix this up once we work out how to remove the beta feed.

I've tested the code currently in the `fb-2020.ts` on a friend's feed, and it seems to remove the feed only for about a second, then the feed reappears. What I'm guessing is happening is that React is rerendering the feed component whenever there's a change inside the feed, and that diff just happens to re-add the contents of the div we removed.

My current thoughts are to try an approach that adds 'display: none' to the feed, then injects a sibling div that React is unaware of which contains the news feed eradicator UI. The trouble with `display: none` is that we might still trigger infinite scrolling mechanisms, which caused problems in fb classic (see #25 #26 #30).

**Comment by samvanemelen** [comment]
I also had friends who didn't get the notification of the update, but they all had the option to switch to it. Have you checked the arrow in the top right? There you should have an option to switch to the new facebook. I absolutely love the eradicator, I'll see if I have some time soon to tinker about it as well!

![image](https://user-images.githubusercontent.com/36103001/78454033-c7a67100-7695-11ea-8997-57fa111a7569.png)

**Comment by jordwest** [comment]
> Have you checked the arrow in the top right? There you should have an option to switch to the new facebook.

Yep unfortunately this is all I see:

![fb](https://user-images.githubusercontent.com/416133/78465597-1d812480-773b-11ea-87be-97175b70733e.png)

**Comment by terencejeong** [comment]
> I've tested the code currently in the `fb-2020.ts` on a friend's feed, and it seems to remove the feed only for about a second, then the feed reappears. What I'm guessing is happening is that React is rerendering the feed component whenever there's a change inside the feed, and that diff just happens to re-add the contents of the div we removed.

> My current thoughts are to try an approach that adds 'display: none' to the feed, then injects a sibling div that React is unaware of which contains the news feed eradicator UI. The trouble with `display: none` is that we might still trigger infinite scrolling mechanisms, which caused problems in fb classic (see #25 #26 #30).

Playing around with it, I think your hypothesis on React is re-rendering the feed component is correct. It also makes it difficult because I think they are using some form of React Suspense. 

I've come up with a primitive example but it does work. I am keen to hear what you think. 

```js
const config = { attributes: true, childList: true, subtree: true };
const observer = new MutationObserver(callback);

document.addEventListener('readystatechange', event => {
  if (event.target.readyState === "complete") {
    // This will target the news feed.
    const newsFeedContainer = event.srcElement.querySelector('div[role="main"]');
    newsFeedContainer.childNodes[0].classList.add('newsFeed');
    newsFeedContainer.childNodes[0].setAttribute('style', 'display: none !important');
    newsFeedContainer.classList.add('newsFeedContainer')
    observer.observe(newsFeedContainer, config)
  }
});

function callback(mutationsList) {
  const childList = mutationsList
  .filter(item => item.type === 'childList');
  if (childList.length) {
    return childList.forEach((item, index) => {
      if (item.target.parentNode.className.includes('newsFeed') && index === 0) {
        item.target.parentNode.outerHTML = '<h1>Yes the 8th</h1>'
        return observer.disconnect();
      }
    })
  }
  
}

```

**Comment by jordwest** [comment]
Ah interesting, thanks for taking a look @terencejeong. Mutation observers are a nice idea. I'm curious how often the mutation occurs while the page is open, could you chuck a console log in the callback there and see how frequently it's called?

**Comment by terencejeong** [comment]
Hey @jordwest because we call ```js observer.disconnect()``` we only get one mutation. I've just forked the repo and will create a more refined version for you to look at 😄

**Comment by reciosonny** [comment]
@jordwest Hi, I thought it would be great to help to get this to work in the new FB theme so I'm inspecting the code to apply some fixes.

With that said, I want to ask if it would be a good idea to dispatch an action inside `fb-2020.ts`? The thing is when the user switched over to dark theme, it's hard to see the quotes visibility:

![image](https://user-images.githubusercontent.com/4612024/80269933-cab9dd80-86e6-11ea-8515-a10492b1049e.png)

So I come up with this initial solution by changing the text color of the quote through dispatching actions:

```javascript
import { removeNode } from '../lib/remove-news-feed';
import injectUI, { isAlreadyInjected } from '../lib/inject-ui';
import isEnabled from '../lib/is-enabled';

//export function checkSite(): boolean {
//	return !!document.querySelector('#stream_pagelet');
//}

export function eradicate() {
	// This delay ensures that the elements have been created by Facebook's
	// scripts before we attempt to replace them
	function eradicateRetry() {
		if (!isEnabled()) {
			return;
		}

		// Don't do anything if the FB UI hasn't loaded yet
		const feed = document.querySelector('[role=feed]');
		const fbTheme = document.querySelector("html");


		if (feed == null) {
			return;
		}

		if (fbTheme.className === "__fb-dark-mode") {
			//todo: dispatch action here so we can change the text color of quote to white
		}

		const container = feed.parentNode;
		removeNode(feed);

		// Add News Feed Eradicator quote/info panel
		if (!isAlreadyInjected()) {
			injectUI(container);
		}
	}

	setInterval(eradicateRetry, 1000);
}
```

Let me know your thoughts.

**Comment by jordwest** [comment]
Hey @reciosonny, yep we could do that, but I think we might be able to save some JS and just use the injected CSS to override the text color. Something like:

```css
.__fb-dark-mode .nfe-container {
  color: white;
}
```

In any case some good news, I woke up this morning to the new beta on my account! So I can finally start working on this 🎉

**Comment by reciosonny** [comment]
@jordwest Awesome! Yeah, I didn't think about injecting it to CSS directly. Great solution.

**Comment by reciosonny** [comment]
I just made a PR for the fix. Check it out: https://github.com/jordwest/news-feed-eradicator/pull/83

**Comment by jordwest** [comment]
Good news! The fix is working locally, I've submitted an update to the Chrome and Firefox add-on stores. They'll be in review for a bit, so keep an eye out for version 1.2.2 over the next few days or so.

Thanks for the help everyone! ❤️ 

I'll close this issue for now, but please do open a new issue if you do see any problems.

![Facebook](https://user-images.githubusercontent.com/416133/80300178-bc9ab880-87dd-11ea-829e-a147c7fea5c9.png)

**Comment by jordwest** [comment]
And dark mode, courtesy of @reciosonny

![Facebook](https://user-images.githubusercontent.com/416133/80300234-37fc6a00-87de-11ea-9aea-ef9541f839ef.png)
