### ISSUE TITLE
Whitelist/Blacklist certain pages or people

### ISSUE THREAD

**Issue by deweysia** [jordwest/news-feed-eradicator#91]
Use case: Sometimes there are certain updates that are nice to receive such as local news posts. To keep updated on certain events, it'd be nice to be able to whitelist or blacklist certain pages or people.

**Comment by jordwest** [comment]
Hi @deweysia, thanks for the suggestion! This would involve a lot of inspection of the feed (and a lot of work to keep it working with Facebook constantly changing their feed) so it's outside the scope of News Feed Eradicator.

In the normal Facebook interface, you can already choose not to see certain people in the feed, or another technique I've heard people use is to "hide" everybody, then just add back the people/pages you want to see.
