### ISSUE TITLE
Option to activate on common social medias

### ISSUE THREAD

**Issue by ujeshkrishnan** [jordwest/news-feed-eradicator#93]
I will be great if you can add an option to enable the eradicator to LinkedIn, Twitter, Quora, YouTube and Instagram. 

This will be really helpful to detox from them too.

**Comment by jordwest** [comment]
Hi @ujeshkrishnan - Twitter support has actually just landed on Firefox as of yesterday, Chrome to follow very soon. I hope to add support for the other sites too, follow #63 for updates
