### ISSUE TITLE
[Feature Request] Reddit feed eradicator?

### ISSUE THREAD

**Issue by samgermain** [jordwest/news-feed-eradicator#96]
I use reddit to ask questions that I need answered for my job, and also other other questions. I find myself being distracted by all the other content when I visit the site though.

I could possibly help out with this (likely not, I'll probably get unmotivated and confused) but I would need some directions on what the look at in this code, as many details as you can write down in 5-10 minutes so that I know exactly which code is important and which isn't.

**Comment by kessido** [comment]
Was thinking about the same thing...!

**Comment by kessido** [comment]
#98 Added a pull request.

**Comment by samgermain** [comment]
@kessido Wow thanks

**Comment by samgermain** [comment]
Is that update only for chrome?

**Comment by kessido** [comment]
Not sure, only tested on chrome.

**Comment by jordwest** [comment]
#98 worked on Firefox for me 👍

**Comment by samgermain** [comment]
@jordwest I'm not seeing the reddit feature when I download the extension from the chrome web store. Do I need to download the github repo and install the extension from that somehow? I've never done that.

**Comment by jordwest** [comment]
Hi @samgermain, I finally just got around to testing and releasing this - version 2.1.0 should have the Reddit support which has just gone to the Chrome web store for review. You should see it roll out over the next few days.
