### ISSUE TITLE
Twitter still loading feed

### ISSUE THREAD

**Issue by bingobangorat** [jordwest/news-feed-eradicator#99]
If I go to twitter.com/home in the url bar, it pulls up the quote as expected, but on twitter.com the the quotes will not load, and the feed loads as normal.

**Comment by edbltn** [comment]
Getting the same problem. Screenshot for reference:

![image](https://user-images.githubusercontent.com/20174907/96051912-7f3cec80-0e4a-11eb-9337-a1a293890bc3.png)

**Comment by jordwest** [comment]
Fixed in 5f79a1fd1febfaac173448072a2aa35e355abd6e
